name: build

on: 
  #push:
   # branches:
   # - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [K2P,RT-AC85P,CR660x]
        toolchain: [mipsel-linux-musl]
    steps:
      - uses: actions/checkout@main
      - uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ matrix.target }}-${{ matrix.toolchain }}
      - uses: actions/setup-go@main
        with:
          go-version: '1.23.0'
          check-latest: true
          cache: false
      - name: Prepare environment
        run: |
          sudo apt-get update && sudo apt-get install -y libtool-bin gperf python3-docutils autopoint gettext ccache
          echo "ROOTDIR=${{ github.workspace }}/trunk" >> $GITHUB_ENV
          echo "Compilation_time=$(TZ='Asia/Shanghai' date +%Y%m%d)" >> $GITHUB_ENV
      - name: Start build firmware
        run: |
          make ${{ matrix.target }} TOOLCHAIN=${{ matrix.toolchain }}
      - uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.target }}-${{ matrix.toolchain }}
          path: trunk/images/*.trx
  publish:
    needs: [build]
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Set Tag Name
        run: echo "TAG_NAME=$(date +%Y%m%d)" >> $GITHUB_ENV
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.TAG_NAME }}
          force_push_tag: true
      - uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.sha }}
          tag: ${{ env.TAG_NAME }}
          artifacts: "mipsel-linux-musl/*.trx"
          allowUpdates: true
          omitBodyDuringUpdate: true
      - uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1